	var jsdivus =
		"<h2 id='atas'></br>JUDUL</h2>"+
		"<p style='text-align:justify'>By downloading or using this NAMAAPK app (hereinafter referred to as SERVICE), this JUDUL will automatically apply to you (hereinafter referred to as USER). Therefore, USER should make sure that USER read this JUDUL carefully before using SERVICE.</p>"+
		"<h3>Modification</h3>"+
		"<p style='text-align:justify'>USER is not allowed to modify SERVICE, any part of SERVICE, in any way. USER is not allowed to attempt to extract the source code of SERVICE, and USER also shouldn't try to translate SERVICE into other languages, or make derivative versions. SERVICE itself still belongs to NAMARTF (hereinafter referred to as PROVIDER).</p>"+
		"<h3>Privacy and Security</h3>"+
		"<p style='text-align:justify'>SERVICE may stores and processes personal data that USER has provided to PROVIDER in order to provide this SERVICE. Further details regarding personal data can be found in <a href='HREFPPTNC'><u>LINKPPTNC</u></a>.</p>"+
		"<p style='text-align:justify'>It's USER's responsibility to keep secure of USER's device which has SERVICE installed, and its access to SERVICE as well. Therefore, PROVIDER recommends that USER does not jailbreak or root USER's device, which is the process of removing software restrictions and limitations imposed by the official operating system of USER's device. It could make USER's device vulnerable to malwares, viruses, malicious programs, and compromise USER's device's security features and it could mean that SERVICE won't work properly or at all.</p>"+
		"<h3>Service Use</h3>"+
		"<p style='text-align:justify'>USER should be aware that there are certain things that PROVIDER will not take responsibility for. Certain functions of SERVICE will require an active internet connection. The connection can be Wi-Fi or provided by USER's mobile network provider, but PROVIDER cannot be held responsible for SERVICE not working at full functionality if USER does not have access to Wi-Fi and USER does not have enough mobile data quota left.</p>"+
		"<p style='text-align:justify'>If USER uses SERVICE outside of an area with Wi-Fi, USER should note that terms of USER's agreement with USER's mobile network provider will still apply. USER may be charged by USER's mobile service provider for data charges during connection while accessing SERVICE, or other third party charges. In using SERVICE, USER accepts responsibility for such charges, including roaming data charges if USER uses SERVICE outside of USER's home territory (i.e. region or country) without turning off roaming data. If USER is not the bill payer for the device on which USER is using SERVICE, please note that PROVIDER considers that USER has obtained permission from the bill payer to use SERVICE.</p>"+
		"<p style='text-align:justify'>Along the same lines, PROVIDER cannot always be responsible for the way USER uses SERVICE, i.e. USER must ensure that USER's device remains charged. If USER's device runs out of battery and USER cannot turn it on to use SERVICE, PROVIDER cannot accept responsibility.</p>"+
		"<h3>Updates</h3>"+
		"<p style='text-align:justify'>PROVIDER is committed to ensuring that SERVICE is as useful and efficient as possible. For that reason, PROVIDER has the right to make changes to SERVICE at any time and for any reason.</p>"+
		"<p style='text-align:justify'>With respect to PROVIDER's responsibility for USER's use of SERVICE, when USER is using SERVICE, it's important to bear in mind that although PROVIDER always tries to ensure that SERVICE is updated and corrected at all times, PROVIDER relies on third parties to provide information to PROVIDER so that PROVIDER can make it available to USER. PROVIDER accepts no liability for any loss, direct or indirect, that USER experiences as a result of relying entirely on the functionality of SERVICE.</p>"+
		"<p style='text-align:justify'>At some point, PROVIDER may need to update SERVICE. SERVICE is currently available on Google Play Store. The requirements for system (and for any additional systems PROVIDER decides to extend the availability of SERVICE to) may change, and USER will need to download the updates if USER wishes to continue using SERVICE. SERVICE's functionality may not work, either in part or in whole, if USER does not update SERVICE to its latest version. PROVIDER does not promise to always update SERVICE so that it is relevant to USER and/or works with the version that USER has installed on USER's device. However, USER promises to always accept SERVICE's updates when they are offered to USER.</p>"+
		"<p style='text-align:justify'>PROVIDER may also wish to stop providing SERVICE, and may terminate use of  SERVICE at any time without notice of termination to USER. Unless PROVIDER notifies USER otherwise, upon any termination, (a) the rights and licenses granted to USER in these terms will terminate; (b) USER must stop from using SERVICE, and (if necessary) delete it from USER's device.</p>"+
		"<h3 id='inappur'>In-App Purchase</h3>"+
		"<p style='text-align:justify'>Through in-app purchase feature, PROVIDER provides products that can be purchased by USER (hereinafter referred to as PRODUCT) in the form of ad removal service.</p>"+
		"<p style='text-align:justify'>In accordance with Google's terms, purchases within SERVICE must be managed using Google Play Billing system, this includes details, purchasing system, and PRODUCT payments. All payments by USER to purchase PRODUCT can only be made via Google Play Billing. PROVIDER only provides PRODUCT within SERVICE, and PROVIDER cannot be held responsible if USER purchases products outside SERVICE including, but not limited to, purchase of products as a result of USER's interaction with ads.</p>"+
		"<p style='text-align:justify'>USER can purchase the desired PRODUCT as long as PRODUCT is available in SERVICE. USER can also purchases PRODUCT to extend the active period of previously purchased PRODUCT. PRODUCT that has been purchased by USER on a Google Play account will only apply to that account, and does not apply to other Google Play account(s). PROVIDER cannot be responsible if USER cannot enjoy the benefit of PRODUCT that has been purchased because USER uses another Google Play account when using SERVICE. The benefits of PRODUCT that USER has purchased only apply to SERVICE itself and do not apply to other applications, whether owned by PROVIDER or not. When USER purchases PRODUCT, please note that PROVIDER considers that USER has understood the terms of purchasing via Google Play including, but not limited to, purchase statuses that cannot be transferred from one Google Play account to another Google Play account.</p>"+
		"<p style='text-align:justify'>When making a payment, USER may be charged additional fees for taxes that apply according to the policies in the region or country where USER is detected using SERVICE.</p>"+
		"<p style='text-align:justify'>PROVIDER always tries to provide relevant PRODUCT offers for USER in using SERVICE. For that reason, PROVIDER has the right to set and change type, price, availability, and promo of PRODUCT, or remove all PRODUCT offers to USER. The benefits of PRODUCT that has been purchased by USER will not change and can still be enjoyed as long as PRODUCT's active period has not ended. PROVIDER can apply different types, prices, or promos, or remove PRODUCT for certain locations. Changes to PRODUCT will be displayed on the page where USER can purchase PRODUCT, so USER must ensure that USER has reviewed and read the informations on the page carefully before purchasing PRODUCT, especially in the sections that are closely related to PRODUCT to be purchased by USER. PROVIDER cannot be held responsible if USER cannot purchase PRODUCT that USER desires due to changes in PRODUCT.</p>"+
		"<p style='text-align:justify'>PROVIDER cannot be held responsible if an error occurs on USER's part when purchasing PRODUCT including, but not limited to, purchase of PRODUCT by another party via USER's device due to access granted by USER to another party, or an error due to USER's carelessness when purchasing PRODUCT.</p>"+
		"<h3>Refunds</h3>"+
		"<p style='text-align:justify'>As payments for purchasing PRODUCT are made via Google Play, refunds are made via Google Play as well. USER can request a refund if it meets the refund terms and conditions set out in Google Play policy. It is recommended that USER reviews the terms, conditions, and steps of requesting a refund in Google Play policy <a href='REFUNDGOOGLE'><u>here</u></a>.</p>"+
		"<h3>Children</h3>"+
		"<p style='text-align:justify'>SERVICE is not intended for children under the age of 13. If USER is under the age of 13, it is recommended that USER obtains parental or guardian supervision when using SERVICE, and PROVIDER considers that USER has obtained permission from the bill payer when purchasing PRODUCT.</p>"+
		"<h3>Changes to This JUDUL</h3>"+
		"<p style='text-align:justify'>PROVIDER may update this JUDUL from time to time. Thus, USER is advised to review this page periodically for any changes. PROVIDER will notify USER of any changes by posting the new JUDUL on this page. Such changes are effective immediately after being posted on this page.</p>"+
		"<h3>Contact Us</h3>"+
		"<p style='text-align:justify'>If USER has any questions or suggestions about this JUDUL, USER may contact PROVIDER at EMAILRTF.</p>"+
		"<p style='text-align:center'></br></br></br></br>Last updated on August 26, 2024.</br></br></p>";




	var jsdivid =
		"<h2 id='atas'></br>JUDUL</h2>"+
		"<p style='text-align:justify'>Dengan mengunduh atau menggunakan aplikasi NAMAAPK (selanjutnya disebut sebagai LAYANAN) ini, JUDUL ini akan berlaku secara otomatis untuk Anda (selanjutnya disebut sebagai PENGGUNA). Karena itu, PENGGUNA harus memastikan bahwa PENGGUNA membaca JUDUL ini dengan cermat sebelum menggunakan LAYANAN.</p>"+
		"<h3>Modifikasi</h3>"+
		"<p style='text-align:justify'>PENGGUNA tidak diperbolehkan memodifikasi LAYANAN, bagian apa pun dari LAYANAN, dengan cara apa pun. PENGGUNA tidak diizinkan untuk mencoba mengekstrak kode sumber LAYANAN, dan PENGGUNA juga tidak boleh mencoba menerjemahkan LAYANAN ke dalam bahasa lain, atau membuat versi turunan. LAYANAN sendiri masih milik NAMARTF (selanjutnya disebut sebagai PENYEDIA).</p>"+
		"<h3>Privasi dan Keamanan</h3>"+
		"<p style='text-align:justify'>LAYANAN mungkin menyimpan dan memproses data pribadi yang telah PENGGUNA berikan kepada PENYEDIA untuk menyediakan LAYANAN ini. Penjelasan lebih lanjut mengenai data pribadi dapat ditemukan di <a href='HREFPPTNC'><u>LINKPPTNC</u></a>.</p>"+
		"<p style='text-align:justify'>Adalah tanggung jawab PENGGUNA untuk menjaga perangkat PENGGUNA yang terpasang LAYANAN tetap aman, begitu juga dengan akses ke LAYANAN. Karena itu, PENYEDIA menyarankan PENGGUNA untuk tidak melakukan <i>jailbreak</i> atau melakukan <i>root</i> pada perangkat PENGGUNA tersebut, yang merupakan proses menghilangkan pelarangan-pelarangan dan pembatasan-pembatasan perangkat lunak yang diberlakukan oleh sistem operasi resmi perangkat PENGGUNA. Itu bisa membuat perangkat PENGGUNA rentan terhadap perangkat perusak, virus, program jahat, dan membahayakan fitur-fitur keamanan perangkat PENGGUNA dan itu berarti bahwa LAYANAN tidak akan berfungsi dengan baik atau tidak sama sekali.</p>"+
		"<h3>Penggunaan Layanan</h3>"+
		"<p style='text-align:justify'>PENGGUNA harus menyadari bahwa ada hal-hal tertentu yang PENYEDIA tidak akan bertanggung jawab atasnya. Fungsi-fungsi tertentu dari LAYANAN akan membutuhkan koneksi internet aktif. Koneksi dapat berupa Wi-Fi atau disediakan oleh penyedia jaringan seluler PENGGUNA, tetapi PENYEDIA tidak dapat bertanggung jawab atas LAYANAN yang tidak berfungsi pada fungsionalitas penuh jika PENGGUNA tidak memiliki akses ke Wi-Fi dan PENGGUNA tidak memiliki kuota data seluler yang tersisa.</p>"+
		"<p style='text-align:justify'>Jika PENGGUNA menggunakan LAYANAN di luar area dengan Wi-Fi, PENGGUNA harus ingat bahwa ketentuan perjanjian PENGGUNA dengan penyedia jaringan seluler PENGGUNA akan tetap berlaku. Akibatnya, PENGGUNA mungkin dikenai biaya oleh penyedia layanan seluler PENGGUNA untuk biaya data selama koneksi berlangsung saat mengakses LAYANAN, atau biaya pihak ketiga lainnya. Dalam menggunakan LAYANAN, PENGGUNA menerima tanggung jawab atas tagihan semacam itu, termasuk biaya data <i>roaming</i> jika PENGGUNA menggunakan LAYANAN di luar wilayah rumah PENGGUNA (misalnya daerah atau negara) tanpa mematikan data <i>roaming</i>. Jika PENGGUNA bukan pembayar tagihan untuk perangkat yang PENGGUNA pakai untuk menggunakan LAYANAN, harap diperhatikan bahwa PENYEDIA menganggap bahwa PENGGUNA telah mendapatkan izin dari pembayar tagihan untuk menggunakan LAYANAN.</p>"+
		"<p style='text-align:justify'>Sejalan dengan itu, PENYEDIA tidak selalu dapat bertanggung jawab atas cara PENGGUNA menggunakan LAYANAN, yaitu PENGGUNA harus memastikan bahwa perangkat PENGGUNA tetap terisi daya. Jika perangkat PENGGUNA kehabisan daya baterai dan PENGGUNA tidak dapat menyalakannya untuk memanfaatkan LAYANAN, PENYEDIA tidak dapat menerima tanggung jawab.</p>"+
		"<h3>Pembaruan</h3>"+
		"<p style='text-align:justify'>PENYEDIA berkomitmen untuk memastikan bahwa LAYANAN bermanfaat dan seefisien mungkin. Untuk alasan itu, PENYEDIA berhak untuk membuat perubahan pada LAYANAN kapan saja dan untuk alasan apa pun.</p>"+
		"<p style='text-align:justify'>Sehubungan dengan tanggung jawab PENYEDIA untuk penggunaan PENGGUNA atas LAYANAN, ketika PENGGUNA menggunakan LAYANAN, penting untuk diingat bahwa meskipun PENYEDIA selalu berupaya memastikan bahwa LAYANAN diperbarui dan diperbaiki setiap saat, PENYEDIA mengandalkan pihak ketiga untuk memberikan informasi kepada PENYEDIA sehingga PENYEDIA dapat menyediakannya untuk PENGGUNA. PENYEDIA tidak bertanggung jawab atas kerugian, langsung atau tidak langsung, yang PENGGUNA alami sebagai akibat sepenuhnya mengandalkan fungsi LAYANAN.</p>"+
		"<p style='text-align:justify'>Pada titik tertentu, PENYEDIA mungkin perlu untuk memperbarui LAYANAN. LAYANAN saat ini tersedia di Google Play Store. Persyaratan untuk sistem (dan untuk sistem tambahan apa pun yang PENYEDIA putuskan untuk memperpanjang ketersediaan LAYANAN) dapat berubah, dan PENGGUNA harus mengunduh pembaruan jika PENGGUNA ingin tetap menggunakan LAYANAN. Fungsionalitas LAYANAN mungkin tidak bekerja, baik sebagian atau keseluruhan, jika PENGGUNA tidak memperbarui LAYANAN ke versi terbaru. PENYEDIA tidak berjanji akan selalu memperbarui LAYANAN sehingga relevan bagi PENGGUNA dan/atau berfungsi dengan versi yang telah PENGGUNA pasang di perangkat PENGGUNA. Namun, PENGGUNA berjanji untuk selalu menerima pembaruan LAYANAN ketika ditawarkan kepada PENGGUNA.</p>"+
		"<p style='text-align:justify'>PENYEDIA mungkin juga ingin berhenti menyediakan LAYANAN, dan dapat menghentikan penggunaan LAYANAN setiap saat tanpa pemberitahuan pengakhiran kepada PENGGUNA. Kecuali PENYEDIA memberi tahu PENGGUNA sebaliknya, pada setiap penghentian, (a) hak dan lisensi yang diberikan kepada PENGGUNA dalam ketentuan ini akan berakhir; (b) PENGGUNA harus berhenti menggunakan LAYANAN, dan (jika perlu) menghapusnya dari perangkat PENGGUNA.</p>"+
		"<h3 id='inappur'>Pembelian di dalam Aplikasi</h3>"+
		"<p style='text-align:justify'>Melalui fitur pembelian di dalam aplikasi, PENYEDIA menyediakan produk-produk (selanjutnya disebut sebagai PRODUK) yang dapat dibeli oleh PENGGUNA berupa layanan penghapusan iklan.</p>"+
		"<p style='text-align:justify'>Sesuai dengan ketentuan dari Google, pembelian di dalam LAYANAN harus dikelola menggunakan sistem Penagihan Google Play, hal ini meliputi rincian, sistem pembelian, serta pembayaran PRODUK. Seluruh pembayaran oleh PENGGUNA untuk membeli PRODUK hanya dapat dilakukan melalui Penagihan Google Play. PENYEDIA hanya menyediakan PRODUK di dalam LAYANAN, dan PENYEDIA tidak dapat bertanggung jawab apabila PENGGUNA melakukan pembelian produk di luar LAYANAN termasuk, namun tidak terbatas pada, pembelian produk sebagai hasil dari interaksi PENGGUNA dengan iklan.</p>"+
		"<p style='text-align:justify'>PENGGUNA dapat membeli PRODUK yang diinginkan selama PRODUK tersedia di dalam LAYANAN. PENGGUNA juga dapat membeli PRODUK untuk memperpanjang masa aktif dari PRODUK yang telah dibeli sebelumnya. PRODUK yang telah dibeli oleh PENGGUNA pada suatu akun Google Play hanya akan berlaku pada akun tersebut, dan tidak berlaku pada akun Google Play lain. PENYEDIA tidak dapat bertanggung jawab apabila PENGGUNA tidak bisa menikmati manfaat dari PRODUK yang telah dibeli karena menggunakan akun Google Play lain saat menggunakan LAYANAN. Manfaat PRODUK yang telah dibeli PENGGUNA hanya berlaku untuk LAYANAN itu sendiri dan tidak berlaku untuk aplikasi-aplikasi lain, baik milik PENYEDIA ataupun bukan. Ketika PENGGUNA melakukan pembelian PRODUK, perlu diketahui bahwa PENYEDIA menganggap PENGGUNA telah memahami perihal pembelian melalui Google Play termasuk, namun tidak terbatas pada, status pembelian yang tidak dapat dipindahkan dari satu akun Google Play ke akun Google Play lainnya.</p>"+
		"<p style='text-align:justify'>Pada saat melakukan pembayaran, PENGGUNA mungkin akan dikenakan biaya tambahan untuk pajak yang berlaku sesuai kebijakan di wilayah atau negara di mana PENGGUNA terdeteksi menggunakan LAYANAN.</p>"+
		"<p style='text-align:justify'>PENYEDIA senantiasa berupaya memberikan penawaran-penawaran PRODUK yang relevan bagi PENGGUNA di dalam menggunakan LAYANAN. Untuk alasan itu, PENYEDIA berhak untuk menetapkan dan mengubah jenis, harga, ketersediaan, serta promo PRODUK, ataupun meniadakan penawaran-penawaran PRODUK sama sekali kepada PENGGUNA. Manfaat dari PRODUK yang telah dibeli oleh PENGGUNA tidak akan berubah dan masih dapat dinikmati selama masa aktif PRODUK belum berakhir. PENYEDIA dapat memberlakukan perbedaan jenis, harga, maupun promo, atau meniadakan PRODUK untuk lokasi tertentu. Perubahan-perubahan pada PRODUK akan ditampilkan di halaman di mana PENGGUNA dapat membeli PRODUK, maka PENGGUNA harus memastikan bahwa PENGGUNA telah meninjau dan membaca informasi-informasi di halaman tersebut dengan cermat sebelum membeli PRODUK, khususnya pada bagian-bagian yang berkaitan erat dengan PRODUK yang akan dibeli oleh PENGGUNA. PENYEDIA tidak dapat bertanggung jawab apabila PENGGUNA tidak dapat membeli PRODUK yang diinginkan PENGGUNA karena perubahan pada PRODUK.</p>"+
		"<p style='text-align:justify'>PENYEDIA tidak dapat bertanggung jawab apabila terjadi kesalahan dari pihak PENGGUNA saat pembelian PRODUK termasuk, namun tidak terbatas pada, pembelian PRODUK oleh pihak lain melalui perangkat milik PENGGUNA karena akses yang diberikan oleh PENGGUNA kepada pihak lain, atau kesalahan karena kekurangcermatan PENGGUNA saat membeli PRODUK.</p>"+
		"<h3>Pengembalian Dana</h3>"+
		"<p style='text-align:justify'>Sebagaimana pembayaran untuk pembelian PRODUK dilakukan melalui Google Play, maka pengembalian dana juga dilakukan melalui Google Play. PENGGUNA dapat mengajukan pengembalian dana jika memenuhi syarat dan ketentuan pengembalian dana yang telah ditetapkan dalam kebijakan Google Play. Disarankan bagi PENGGUNA untuk meninjau syarat, ketentuan, serta langkah-langkah pengajuan pengembalian dana dalam kebijakan Google Play <a href='REFUNDGOOGLE'><u>di sini</u></a>.</p>"+
		"<h3>Anak-anak</h3>"+
		"<p style='text-align:justify'>LAYANAN tidak ditujukan untuk anak-anak berusia di bawah 13 tahun. Jika PENGGUNA berusia di bawah 13 tahun, disarankan untuk mendapatkan pendampingan dari orang tua atau wali saat menggunakan LAYANAN, dan PENYEDIA menganggap bahwa PENGGUNA telah mendapatkan izin dari pembayar tagihan saat membeli PRODUK.</p>"+
		"<h3>Perubahan pada JUDUL Ini</h3>"+
		"<p style='text-align:justify'>PENYEDIA dapat memperbarui JUDUL ini dari waktu ke waktu. Dengan demikian, PENGGUNA disarankan untuk meninjau halaman ini secara berkala untuk setiap perubahan. PENYEDIA akan memberi tahu PENGGUNA tentang segala perubahan dengan mengeposkan JUDUL di halaman ini. Perubahan tersebut berlaku segera setelah diposkan di halaman ini.</p>"+
		"<h3>Hubungi Kami</h3>"+
		"<p style='text-align:justify'>Jika PENGGUNA memiliki pertanyaan atau saran tentang JUDUL ini, PENGGUNA dapat menghubungi PENYEDIA di EMAILRTF.</p>"+
		"<p style='text-align:center'></br></br></br></br>Terakhir diperbarui pada 26 Agustus 2024.</br></br></p>";
		